services:
  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
      - mariadb
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - web:/var/www/html
    ports:
      - "80:80"
    restart: on-failure

  wordpress:
    container_name: wp-php
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - web:/var/www/html
    expose:
      - "9000"
    depends_on:
      - mariadb
    secrets:
      - wp_password
      - db_password
    env_file:
      - .env
    restart: on-failure

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - database:/var/lib/mysql
    expose:
      - "3306"
    secrets:
      - db_password
    env_file: .env
    restart: unless-stopped

networks:
  inception:

secrets:
  wp_password:
    file: ../secrets/wordpress_admin_password.txt
  db_password:
    file: ../secrets/db_password.txt

volumes:
  database:
    name: database
    driver: local
    driver_opts:
        type: 'none'
        o: 'bind'
        device: '/home/ziggy/data/database' 
  web:
    name: web
    driver: local
    driver_opts:
        type: 'none'
        o: 'bind'
        device: '/home/ziggy/data/web' 